#!/bin/sh

if [ "$(uname)" = "Linux" ]; then
	chosen=$(\
		lsblk --noheadings --raw -o \
		NAME,SIZE,TYPE,FSTYPE,MOUNTPOINT |\
		awk '$3 == "part" && $5 == ""' |\
		dmenu -i -p "Mount volume" -l 10 )
	partition=$(echo "$chosen" | awk '{print $1}')
	file_type=$(echo "$chosen" | awk '{print $4}')

	if [ "$file_type" = "crypto_LUKS" ]; then
		dev=dev/mapper
	else # file_type != crypto_LUKS
		dev=dev
	fi
fi

[ "$file_type" = "vfat" ] && mount_option="-o rw,umask=0000"

# Mount partition
[ ! "$partition" ] && exit 0
mount_point=$(find /mnt/ -maxdepth 1 -type d -empty | sort |\
	dmenu -i -p "Select mount point")
[ ! "$mount_point" ] && exit 0
	echo mount "/$dev/$partition" "$mount_point" "$mount_option"
dmenu -P -p "Mount | sudo " |\
	sudo -S mount /$dev/$partition $mount_point $mount_option\
		&& notify-send "Mounted" "$partition"\
		|| notify-send -u critical "Error Mounting" "$partition"
